import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript', 'prettier'),
  {
    // next-env.d.ts is generated by Next.js and must not be edited or linted.
    ignores: ['.next/**', 'node_modules/**', '.open-next/**', 'design/**', 'next-env.d.ts'],
  },
  {
    rules: {
      // The site copy is French — apostrophes in JSX text are expected and fine.
      'react/no-unescaped-entities': 'off',
    },
  },
];

export default eslintConfig;
